In [1]:
! pwd

/h/DIP_Project/freq-net


# lr_scheduler

In [12]:
from freq_net.model.model import FreqNet

model = FreqNet(n_resgroups=2 , n_depthwise_resgroups=1 , n_resblocks = 3)

num_params = sum(p.numel() for p in model.parameters())
print(f"The model has {num_params} parameters.")

The model has 1624800 parameters.


In [85]:
import torch
import torch.optim as optim
from torch.optim.lr_scheduler import CosineAnnealingLR
import torch.nn as nn
import torch.nn.functional as F


def cossine_lr(optimizer, t_max, eta_min):
    """
    eta_max will be the learning rate of optimizer
    """
    return CosineAnnealingLR(optimizer=optimizer, T_max=t_max, eta_min=eta_min)


class SimpleModel(nn.Module):
    def __init__(self, input_size=1, output_size=1):
        super(SimpleModel, self).__init__()
        self.fc1 = nn.Linear(input_size, output_size)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        return x


model = SimpleModel()
optimizer = optim.Adam(model.parameters(), lr = 8e-5 , betas = (0.9 , 0.99) , eps = 1e-8)

# Define the CosLR scheduler
scheduler = cossine_lr(optimizer,  t_max = 20 , eta_min = 1e-7)


# Train the model
for epoch in range(40):
    # Train the model for one epoch
    train_loss = ...

    # Update the learning rate using the scheduler
    scheduler.step()

    # Print the current learning rate
    print("Epoch:", epoch, "LR:", scheduler.get_lr())

Epoch: 0 LR: [7.90193261632736e-05]
Epoch: 1 LR: [7.660823673347575e-05]
Epoch: 2 LR: [7.332055025267214e-05]
Epoch: 3 LR: [6.923676427917746e-05]
Epoch: 4 LR: [6.445695860172482e-05]
Epoch: 5 LR: [5.909831709737849e-05]
Epoch: 6 LR: [5.329222507748192e-05]
Epoch: 7 LR: [4.718101146477996e-05]
Epoch: 8 LR: [4.09144127030451e-05]
Epoch: 9 LR: [3.4645840000202857e-05]
Epoch: 10 LR: [2.8528532330289877e-05]
Epoch: 11 LR: [2.2711672592470017e-05]
Epoch: 12 LR: [1.733652905977669e-05]
Epoch: 13 LR: [1.2532647922707756e-05]
Epoch: 14 LR: [8.414035832668668e-06]
Epoch: 15 LR: [5.0750438674695244e-06]
Epoch: 16 LR: [2.584980955966816e-06]
Epoch: 17 LR: [9.780232940015221e-07]
Epoch: 18 LR: [2.2372432417573743e-07]
Epoch: 19 LR: [1e-07]
Epoch: 20 LR: [1.083701586448492e-06]
Epoch: 21 LR: [7.873022913467656e-06]
Epoch: 22 LR: [9.796676574016854e-06]
Epoch: 23 LR: [1.3469209498370389e-05]
Epoch: 24 LR: [1.804488557753268e-05]
Epoch: 25 LR: [2.32768557383891e-05]
Epoch: 26 LR: [2.8993067806294252e

d:\Anaconda3\envs\myenv\lib\site-packages\torch\optim\lr_scheduler.py:138: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
d:\Anaconda3\envs\myenv\lib\site-packages\torch\optim\lr_scheduler.py:807: UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.
  warnings.warn("To get the last learning rate computed by the scheduler, "


# dropout

In [1]:
import torch.nn as nn

dropout_rate1 = 0.5
dropout_rate2 = 0.3

# Create the convolutional layers and activation function
l1 = nn.Linear(4 , 10)

conv1 = nn.Conv2d(1, 3, 3)
act = nn.ReLU()
conv2 = nn.Conv2d(3, 6, 3)

# Create the dropout layers
dropout1 = nn.Dropout(dropout_rate1)
dropout2 = nn.Dropout(dropout_rate2)

# Create the sequential module with dropouts
body = nn.Sequential(
    conv1,
    act,
    dropout1,
    conv2,
    dropout2
)

d:\Anaconda3\envs\myenv\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [28]:
import torch
l1 = nn.Linear(2 , 10)
l2 = nn.Linear(2 , 10)
ol1 = l1(torch.tensor([1 , 2 , 3 , 4]).to(torch.float32))
ol2 = l2(torch.tensor([1 , 2 , 3 , 4]).to(torch.float32))
print(ol1)
print()
print(ol2)

tensor([ 1.7138,  0.5866, -0.0728, -0.4723,  3.2172,  2.2049, -3.7183,  0.7901,
        -2.8355,  2.8245], grad_fn=<AddBackward0>)

tensor([-0.3271,  1.8931,  2.0541, -2.0536,  2.7993,  1.6926,  0.4209, -0.7130,
        -0.5047, -3.4515], grad_fn=<AddBackward0>)


In [51]:
dropout1(torch.tensor([1.0 , 2.0 , 3.0]))

tensor([0., 4., 6.])